#!/bin/bash
# Publish a rebuilt dashboard cache. Run this on YOUR machine, from the repo
# root -- never on the server.
#
# The counterpart to docs/deploy.sh. That script consumes what this one
# publishes:
#
#     you:     build_all  ->  git push (Track.db, static/data)
#                         ->  publish.sh (dashboard_cache.db, as a release asset)
#     server:  deploy.sh  ->  clone + curl  ->  reload
#
# dashboard_cache.db is generated, ~12MB, and rewritten whole on every build, so
# it is not in git -- tracking it put a fresh 12MB blob in history on every data
# update. A release asset is replaced in place and costs nothing in clone size.
#
# Creating the release is a one-time thing, so this does it only if it is
# missing. Uploading happens every time the cache changes. You do not have to
# remember which case you are in.
#
# docs/hooks/pre-push calls this automatically when you push main. Running it by
# hand does exactly the same thing.
#
#     ./docs/publish.sh            # prompts if the working tree is dirty
#     ./docs/publish.sh --yes      # never prompts; for hooks and scripts
set -euo pipefail

TAG=cache-latest
CACHE=web/data/dashboard_cache.db

ASSUME_YES=no
[ "${1:-}" = "--yes" ] && ASSUME_YES=yes

# Find gh, falling back to the usual install locations when it is not on PATH.
#
# It is not always on PATH even when it is installed: an editor or terminal
# started before gh was installed keeps the environment it was launched with, and
# a hook run from inside it inherits that. VS Code's git did exactly this -- a
# push blocked by "gh is not installed" on a machine where gh was installed and
# working in every fresh shell. Looking in the standard places turns a confusing
# failure into no failure at all.
GH=""
if command -v gh >/dev/null 2>&1; then
  GH=gh
else
  for candidate in \
    "/c/Program Files/GitHub CLI/gh.exe" \
    "/c/Program Files (x86)/GitHub CLI/gh.exe" \
    "$LOCALAPPDATA/Programs/GitHub CLI/gh.exe" \
    /usr/local/bin/gh \
    /opt/homebrew/bin/gh \
    /usr/bin/gh
  do
    [ -x "$candidate" ] && { GH="$candidate"; break; }
  done
fi

if [ -z "$GH" ]; then
  echo "gh (the GitHub CLI) could not be found."
  echo "  Install it:  winget install --id GitHub.cli   (see https://cli.github.com)"
  echo "  Already installed? The shell running this has a PATH from before the"
  echo "  install -- restart your editor or terminal and try again."
  exit 1
fi
test -f "$CACHE" || {
  echo "$CACHE not found. Run: cd web && python -m app.jobs.build_all"; exit 1; }

# Where we remember what was last published. Inside .git, so it is per-clone and
# never committed -- it describes this machine's relationship to the release,
# not the project.
STATE="$(git rev-parse --git-dir)/last-published-cache"

# ---- do not publish a cache that does not match the results ----
# The cache and Track.db have to land on the server together. Publishing a cache
# built from a different Track.db than the one you are about to push gives the
# server two halves that do not agree -- which deploy.sh will refuse, after you
# have already pushed.
( cd web && python -m app.jobs.build_all --check ) || {
  echo
  echo "ABORTING: the precomputed data is not in step with web/data/Track.db."
  echo "  Rebuild first: cd web && python -m app.jobs.build_all"
  exit 1; }

# ---- is Track.db committed? ----
# The server reads Track.db from git and the cache from the release. Uploading
# the cache while Track.db sits uncommitted means the two arrive out of step.
if ! git diff --quiet HEAD -- web/data/Track.db web/app/static/data; then
  echo "WARNING: Track.db or static/data has uncommitted changes."
  echo "  Commit them, or the server gets this cache with older results."
  if [ "$ASSUME_YES" = yes ] || [ ! -t 0 ]; then
    # No terminal to ask at -- a pre-push hook has git's ref list on stdin, and
    # `read` there would consume that rather than wait for a person. Refusing is
    # the safe default; --yes is how you say you meant it.
    if [ "$ASSUME_YES" != yes ]; then
      echo "  Not running interactively, so stopping. Re-run with --yes to publish anyway."
      exit 1
    fi
    echo "  --yes given; publishing anyway."
  else
    read -r -p "  Publish anyway? [y/N] " reply
    [ "$reply" = "y" ] || { echo "  stopped."; exit 1; }
  fi
fi

# ---- create the release, but only if it is not already there ----
if "$GH" release view "$TAG" >/dev/null 2>&1; then
  echo "Release $TAG exists; replacing its asset."
else
  echo "Release $TAG does not exist yet; creating it."
  "$GH" release create "$TAG" \
    --title "Dashboard cache" \
    --notes "Generated by app.jobs.build_all. Replaced in place on each data update.
Not a version tag -- deploy.sh always downloads this one."
fi

# --clobber replaces the existing asset rather than failing on the name.
"$GH" release upload "$TAG" "$CACHE" --clobber

# Record what we just published, so the pre-push hook can tell whether the cache
# has moved since. Written only after a successful upload -- if the upload fails,
# the next push must try again.
sha256sum "$CACHE" | cut -d' ' -f1 > "$STATE"

echo
echo "Published $(du -h "$CACHE" | cut -f1) to the $TAG release."
echo "If Track.db or static/data changed too, push them before deploying."
