#!/bin/bash
# Publish a rebuilt dashboard cache. Run this on YOUR machine, from the repo
# root -- never on the server.
#
# The counterpart to docs/deploy.sh. That script consumes what this one
# publishes:
#
#     you:     build_all  ->  git push (Track.db, static/data)
#                         ->  publish.sh (dashboard_cache.db, as a release asset)
#     server:  deploy.sh  ->  clone + curl  ->  reload
#
# dashboard_cache.db is generated, ~12MB, and rewritten whole on every build, so
# it is not in git -- tracking it put a fresh 12MB blob in history on every data
# update. A release asset is replaced in place and costs nothing in clone size.
#
# Creating the release is a one-time thing, so this does it only if it is
# missing. Uploading happens every time the cache changes. You do not have to
# remember which case you are in.
set -euo pipefail

TAG=cache-latest
CACHE=web/data/dashboard_cache.db

command -v gh >/dev/null || {
  echo "gh (the GitHub CLI) is not installed -- see https://cli.github.com"; exit 1; }
test -f "$CACHE" || {
  echo "$CACHE not found. Run: cd web && python -m app.jobs.build_all"; exit 1; }

# ---- do not publish a cache that does not match the results ----
# The cache and Track.db have to land on the server together. Publishing a cache
# built from a different Track.db than the one you are about to push gives the
# server two halves that do not agree -- which deploy.sh will refuse, after you
# have already pushed.
( cd web && python -m app.jobs.build_all --check ) || {
  echo
  echo "ABORTING: the precomputed data is not in step with web/data/Track.db."
  echo "  Rebuild first: cd web && python -m app.jobs.build_all"
  exit 1; }

# ---- is Track.db committed and pushed? ----
# The server reads Track.db from git and the cache from the release. Uploading
# the cache while Track.db sits uncommitted means the two arrive out of step.
if ! git diff --quiet HEAD -- web/data/Track.db web/app/static/data; then
  echo "WARNING: Track.db or static/data has uncommitted changes."
  echo "  Commit and push them, or the server gets this cache with older results."
  read -r -p "  Publish anyway? [y/N] " reply
  [ "$reply" = "y" ] || { echo "  stopped."; exit 1; }
fi

# ---- create the release, but only if it is not already there ----
if gh release view "$TAG" >/dev/null 2>&1; then
  echo "Release $TAG exists; replacing its asset."
else
  echo "Release $TAG does not exist yet; creating it."
  gh release create "$TAG" \
    --title "Dashboard cache" \
    --notes "Generated by app.jobs.build_all. Replaced in place on each data update.
Not a version tag -- deploy.sh always downloads this one."
fi

# --clobber replaces the existing asset rather than failing on the name.
gh release upload "$TAG" "$CACHE" --clobber

echo
echo "Published $(du -h "$CACHE" | cut -f1) to the $TAG release."
echo "If Track.db or static/data changed too, push them before deploying."
